#ifndef DDTP_STATE_H
#define DDTP_STATE_H

enum ddtp_State {
  STANDBY,
  PRE_SEND_SESSION_INFO,
  PRE_RECV_SESSION_INFO,
  PRE_SEND_METADATA,
  PRE_RECV_METADATA,
  PRE_SEND_DATA,
  PRE_RECV_DATA,
  SEND_DATA,
  RECV_DATA,
  PRE_SEND_CTRL,
  SEND_CTRL,
  PRE_RECV_CTRL
};

#endif